// import "./globals.css";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "redux-rtk-next-13.4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
